# Generated by Django 5.2.7 on 2025-10-22 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_expansion', models.CharField(max_length=100)),
                ('fecha_lanzamiento', models.DateField()),
                ('total_cartas', models.IntegerField()),
                ('idioma', models.CharField(max_length=50)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
